[package]
name = "quick-fea"
version = "0.1.0"
authors = ["Luke Minnich <squareman2357@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
