name: build-master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - run: rustup component add clippy
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
#     - name: rust-clippy-check
#       uses: actions-rs/clippy-check@v1.0.7
#       with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           args: --all-features
